Fix bytes_in_range (#970)
Our nightly tests found a flaky test:

https://github.com/slatedb/slatedb/actions/runs/19009586090/job/54288529795

The issue appears to be that `minvalue_bytes` can return an empty byte
range with a byte array like this:

```rs
BytesRange::new(
    Bound::Unbounded,
    Bound::Included(Bytes::from_static(&[0; 2])),
);
```

That's technically valid, but `bytes_in_range` expects only non-empty
ranges:

```rs
let result = minvalue_bytes(rng, min_len, max_len);
assert!(
    !result.is_empty(),
    "calculated empty bytes for range {range:?}"
);
```

This results in the following test failure:

```
running 1 test
test proptest_util::tests::test_bytes_in_range_with_multiple_bytes ... FAILED

failures:

---- proptest_util::tests::test_bytes_in_range_with_multiple_bytes stdout ----

thread 'proptest_util::tests::test_bytes_in_range_with_multiple_bytes' panicked at slatedb/src/proptest_util.rs:405:17:
calculated empty bytes for range BytesRange { inner: ComparableRange { start: StartBound { inner: Unbounded }, end: EndBound { inner: Included(b"\0\0") } } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    proptest_util::tests::test_bytes_in_range_with_multiple_bytes

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 756 filtered out; finished in 0.00s

error: test failed, to rerun pass `-p slatedb --lib`
```

I added a test and fixed the issue by forcing `min_len` in
`bytes_in_range` to be `Excluded(0)` if the range start is `Unbounded`.