fix: set Memory as the default of ReadOptions.durability_filter  (#626)
related: #623

```
---- slatedb/src/db.rs - db::Db::get_with_options (line 593) stdout ----
Test executable failed (exit status: 101).

stderr:

thread 'main' panicked at slatedb/src/db.rs:13:5:
assertion `left == right` failed
  left: None
 right: Some(b"value")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

the cause is that `ReadOptions::default()` was setting
`durability_filter: Remote` as default, so the `get()` can not return
the `put()`ed data immediately.