Peg cargo-edit in release to stable rust (#987)
Fix for failed release.yaml process:

```
error: failed to compile `cargo-edit v0.13.7`, intermediate artifacts can be found at `/tmp/cargo-installgPGavV`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  rustc 1.88.0-nightly is not supported by the following package:
    smol_str@0.3.4 requires rustc 1.89
  Try re-running `cargo install` with `--locked`
```