Empty scan ranges cause panic (#681)
SST iterators currently make this check when there are no more fetch
tasks:

```rust
assert_eq!(self.next_block_idx_to_fetch, self.block_idx_range.end);
```

This makes sense in the happy path case where we've traversed blocks in
order. There's a pathological case that causes this code to panic. If a
user scans in such a way that the range's start key > the range's end
key, it causes a panic here with something like:

```
---- sst_iter::tests::test_iter_with_start_key_larger_than_end_key stdout ----

thread 'sst_iter::tests::test_iter_with_start_key_larger_than_end_key' panicked at slatedb/src/sst_iter.rs:295:17:
assertion `left == right` failed
  left: 2
 right: 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    sst_iter::tests::test_iter_with_start_key_larger_than_end_key
```

I was getting this while doing deterministic simulation testing. I've
added a unit test to reproduce and updated the check to allow start
blocks to be `>=` end blocks.