Include timestamp when loading tables for compaction bench (#279)
Currently run the `bencher compaction load` fails with the following
error:
```
thread 'main' panicked at /Users/jason/Code/slatedb/src/compaction_execute_bench.rs:91:18:
join failed: JoinError::Panic(Id(14), "Timestamp RowAttribute was enabled for SST but attempted to insert a row with no timestamp.", ...)
```
This patch just uses current time to provide the missing timestamp. We
could alternatively disable it in the row attributes or provide some
other way to seed the values, but this seemed like the simplest thing
for now.